# for i in range(rows):
#   mapthing.append([None] * cols)
import ID.Terrain
from Dungeon import DungeonCell, TerrainFlags


testmap =   [
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_DOOR_CLOSED, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_SHOP_GENERAL, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_FLOOR, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))],
    [DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True)),DungeonCell(terrain = ID.Terrain.TF_GRANITE, flags = TerrainFlags(True, True, True))]
            ]





