#Edit helper, a few constants for edit files to make them easier to read...

weight = 'weight'
value = 'value'
rarity = 'rarity'
depth = 'depth' 
damage = 'damage'
ac = 'ac'
thrown_damage = 'thrown_damage'
created = 'created'
to_hit = 'to_hit'
to_dam = 'to_dam'
to_ac = 'to_ac'
item_resists = 'item_resists'
resists = 'resists'
vulnerabilities = 'vulnerabilities'
immunities = 'immunities'
flags = 'flags'
powers = 'powers'
effect = 'effect'

id = 'id'
speed = 'speed'
energy = 'energy'
status = 'status'
max_hp = 'max_hp'
max_sp = 'max_sp'
cur_sp = 'cur_sp'
cur_hp = 'cur_hp'